### ISSUE TITLE
Some footprints silkscreen is too large

### ISSUE THREAD

**Issue by mtiutiu** [wokwi/easyeda2kicad#13]
**Description:**
I just converted one of my designs and some capacitors get a pretty large footprint silkscreen drawing.

**Expected result:**
Footprints silkscreen should have the right size after conversion.

See attached pictures.

Original:
![Screenshot from 2020-01-29 15-34-47](https://user-images.githubusercontent.com/2891463/73361679-1eff1e00-42ae-11ea-96af-caa87ac36b3e.png)

Conversion result:
![Screenshot from 2020-01-29 15-35-31](https://user-images.githubusercontent.com/2891463/73361698-24f4ff00-42ae-11ea-90e2-b3860ac7a280.png)

Project files:
[project.zip](https://github.com/wokwi/easyeda2kicad/files/4128328/project.zip)

KiCAD version (latest stable): **5.1.5**
easyeda2kicad version: **1.3.2**

If any other details are needed please let me know.
Thanks.

**Comment by mtiutiu** [comment]
Oh..and I forgot to mention that there are two high voltage symbols in the upper part of the board which are being rendered incomplete after the conversion also (the thunder strike arrow is missing).

**Comment by urish** [comment]
Capacitor issue fixed in aebe5df.

Board outline arc - seems like the start/end or the angle have to be inverted, but I'm not sure what the logic for determining that should be, so it requires further investigation.

As for the high voltage symbols - these are SOLIDREGIONs of type `solid`, which are not currently supported - can you please open another issue for that?

**Comment by mtiutiu** [comment]
@urish Sure. I will open another ticket for the board outline also as it's more ok to be tracked as a separate issue. Thanks.

**Comment by urish** [comment]
Thanks! So we can close this one
